### ISSUE TITLE
A P4, 64x32 RGB matrix panel (I get mine from Aliexpress)?

### ISSUE THREAD

**Issue by Tigwin** [smartbutnot/flightportal#1]
What's that mean, a raspberry pi 4 AND a matrix panel? 

Also I searched alieexpress and there seems to be a bunch to pick from. Can you link the one you picked?

**Comment by smartbutnot** [comment]
P4 is the density of the panel, not a raspberry pi. So any P4 panel of that resolution should be the same size, there will be loads of them but they’re all the same.
