### ISSUE TITLE
URL worked - not anymore

### ISSUE THREAD

**Issue by resmithn** [smartbutnot/flightportal#18]
Looks like Flight Radar pulled the plug on the url. Had it running since late July 2023. Now url returns no flight data.
And will add that the url was probably a form of web-scraping, which FlightRadar frowns on. 
Was fun while it lasted.

**Comment by smartbutnot** [comment]
Are you on the latest version of the code? Still working for me, but you need the version from 2 weeks ago that uses data-cloud instead of data-live in the URL.

**Comment by resmithn** [comment]
Thanks, I missed that comment. Appreciate your reply.
