### ISSUE TITLE
More range ?

### ISSUE THREAD

**Issue by Airbusflotte** [smartbutnot/flightportal#21]
Hello guys,

it’s possible to become more range on my position ? 

Example: 
Coordinate + xxx nm nortical miles?

**Comment by AgentP3** [comment]
You can just calculate the coordinates based on the amount of distance you want to add. The inputs create whatever 4 corners you want so in theory you can have it sweep through any range.On Jan 27, 2024, at 16:40, Airbusflotte ***@***.***> wrote:﻿
Hello guys,
it’s possible to become more range on my position ?
Example:
Coordinate + xxx nm nortical miles?

**Comment by Airbusflotte** [comment]
Thank you, that’s means that I can 4x latitude and 4x longitude ?

**Comment by Airbusflotte** [comment]
I fixit thank you
