### ISSUE TITLE
Update the reference to the ICAO files in the readme

### ISSUE THREAD

**Issue by curtchambers** [smartbutnot/flightportal#3]
Looks like this line needs to be updated in the readme referencing the ICAO files:  "Prep the portal as detailed here (https://learn.adafruit.com/adafruit-matrixportal-m4/prep-the-matrixportal), put the code, secrets **and icao files on**, put your wifi details and the geo box you want to search in the secrets file, and you should be good to go!"

**Comment by smartbutnot** [comment]
Good catch, updated now.
