### ISSUE TITLE
Circuit Python 9

### ISSUE THREAD

**Issue by RunwayNomad** [smartbutnot/flightportal#33]
Has anyone been able to update this code to be compatible with Version 9 of Circuit Python? It seems we need to use a settings.toml file instead of the secrets file. Also some other changes apparently in the code for Circuit Python changed like the show attribute. I'm not very familiar with coding at all thanks!

**Comment by compileByTheMile** [comment]
I've ported the code to CircuitPython v9 see https://github.com/smartbutnot/flightportal/pull/34.

**Comment by RunwayNomad** [comment]
Thanks so much for helping update the code!
